### ISSUE TITLE
Please release asn1-rs with syn 2

### ISSUE THREAD

**Issue by g2p** [rusticata/asn1-rs#29]
I would like to remove syn 1 from my dependency tree (since it's slow to build).  As far as I can tell, the upgrade isn't even breaking (at least given how I use asn1-rs/der-parser/x509-parser).

**Comment by qwandor** [comment]
I'd also appreciate this, it's blocking some updates in the AOSP tree.

**Comment by joshtriplett** [comment]
I'd appreciate this as well.

**Comment by chifflier** [comment]
Hi,
Quick update: asn1-rs 0.6.0 will be released soon, so this will be fixed ASAP.

**Comment by chifflier** [comment]
Hi,
asn1-rs 0.6.0 has been released and uploaded to crates.io.
Closing this issue
Thanks!
