### ISSUE TITLE
Missing license files in asn1-rs-impl-0.2.0.crate

### ISSUE THREAD

**Issue by wojnilowicz** [rusticata/asn1-rs#37]
[LICENSE-MIT](https://github.com/rusticata/asn1-rs/blob/master/LICENSE-MIT) and [LICENSE-APACHE](https://github.com/rusticata/asn1-rs/blob/master/LICENSE-APACHE) are missing in asn1-rs-impl-0.2.0.crate downloaded from https://crates.io/crates/asn1-rs-impl/0.2.0. Would you accept a PR similar to [this one](https://github.com/rwf2/Rocket/issues/2760)? I would like to package it as rpm for Fedora (which identifies missing license as a [mistake](https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text) and encourages upstream to include it) and it would make it easier. Thanks.

**Comment by chifflier** [comment]
Hi,
Indeed, these files are missing, and that is unintentional. This also concerns [asn1-rs-derive](https://crates.io/crates/asn1-rs-derive/), by the way.
These crates are helper crates not really meant to be used directly, but they should have a license file.
Feel free to propose a PR if you want, or I can take care of it if you prefer.
Thank you

**Comment by wojnilowicz** [comment]
Hi, in Fedora there is a tool called rust2rpm which download crates directly from crates.io and converts them to rpms packages. In that way they would be used directly but probably only as a dependency of asn1-rs.

I've posted a relevant PR. Thanks in advance for accepting it.
